services:
  - type: static
    name: epet
    plan: free
    buildCommand: npm install && npm run build:static
    staticPublishPath: dist-static
    autoDeployTrigger: commit
    envVars:
      - key: NODE_VERSION
        value: 22.13.0
